spring:
  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          uim-account:
            url: http://127.0.0.1:28002
            connectTimeout: 5000
            readTimeout: 50000
            loggerLevel: full
          uim:
            url: http://127.0.0.1:28002
            connectTimeout: 5000
            readTimeout: 50000
            loggerLevel: full
#            errorDecoder: com.example.SimpleErrorDecoder
#            retryer: com.example.SimpleRetryer
#            defaultQueryParameters:
#              query: queryValue
#            defaultRequestHeaders:
#              header: headerValue
#            requestInterceptors:
#              - com.example.FooRequestInterceptor
#              - com.example.BarRequestInterceptor
#            responseInterceptor: com.example.BazResponseInterceptor
#            dismiss404: false
#            encoder: com.example.SimpleEncoder
#            decoder: com.example.SimpleDecoder
#            contract: com.example.SimpleContract
#            capabilities:
#              - com.example.FooCapability
#              - com.example.BarCapability
#            queryMapEncoder: com.example.SimpleQueryMapEncoder
#            micrometer.enabled: false

#feign:
#  client:
#    config:
#
#      default: # default全局的配置
#        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
#  okhttp:
#    enabled: false
#  httpclient:
#    enabled: true # 开启feign对HttpClient的支持
#    max-connections: 200 # 最大的连接数
#    max-connections-per-route: 50 # 每个路径的最大连接数


#dows:
#  rpc:
#    uim:
#      url: http://127.0.0.1:28002
#    rbac:
#      url: http://127.0.0.1:8080
#    vac:
#      url: http://localhost:8081

