dows:
  llm:
    clients:
      deepseek-r1:
        enabled: true
        api-url: https://api.deepseek.com/chat/completions
        api-key: sk-e31cfdf43187486db26adba65bd34839
        model: deepseek-reasoner
      deepseek-v3:
        enabled: true
        api-url: https://api.deepseek.com/chat/completions
        api-key: sk-878aecf04c534ac3ab3ba9b3a9a74e86
        model: deepseek-chat
      openai:
        enabled: true
        api-url: https://api.openai.com
        api-key: xxx
        model: openai
      gemini:
        enabled: true
        api-url: https://gemini.google.com
        api-key: xxx
        model: gemini-pro

