dows:
  llm:
    clients:
      deepseek-r1:
        enabled: true
        api-url: https://api.deepseek.com/chat/completions
        api-key: sk-e31cfdf43187486db26adba65bd34839
        model: deepseek-reasoner
      deepseek-v3:
        enabled: true
        api-url: https://api.deepseek.com/chat/completions
        api-key: sk-5317b503f34d40c191c6ee9ea5aef146
        model: deepseek-chat
      openai:
        enabled: true
        api-url: https://api.openai.com
        api-key: xxx
        model: openai
      gemini:
        enabled: true
        api-url: https://gemini.google.com
        api-key: xxx
        model: gemini-pro
      qwen:
        enabled: true
        api-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
        api-key: xxx
        model: qwen-plus

