server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 32
  #  servlet:
  #    context-path: /${spring.application.name}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  application:
    name: dows-gpt
    appId: 1
  profiles:
    include: mysql,apidoc,mybatis,caffeine,ai,thread,hrm,oss,feign,llm,mineru
    active: dev

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    root: info
    org:
      springframework:
        web:
          client=DEBUG:



---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 18001
linkPath: https://hioas.com/pdf/
filePath: /hrm/file
txtPath: /hrm/txt
oss:
  upload:
    callbackUrl: /v1/hrm/resume/file/update/byOss

rade:
  cacheName: hrm
  encryptor:
    enable: true
    algorithm: AES
    secretKey: 3fb2uPksjNOnxZI3

---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
server:
  port: 28001
linkPath: https://hioas.com/pdf/
filePath: /hrm/file
txtPath: /hrm/txt
oss:
  upload:
    callbackUrl: /v1/hrm/resume/file/update/byOss

---
#测试环境
spring:
  config:
    activate:
      on-profile: uat
server:
  port: 38001

---
#测试环境
spring:
  config:
    activate:
      on-profile: prd
server:
  port: 48001